// Uses the same local Vite/Playwright setup as playback-ownership.browser.cjs.
const assert = require('node:assert/strict')
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright')
const base = process.env.TEST_BASE_URL || 'http://127.0.0.1:5174'
const sessionId = 'api-guided-close-test'

;(async () => {
  const browser = await chromium.launch({ channel: process.env.TEST_BROWSER || 'msedge', headless: true })
  const page = await browser.newPage(process.env.TEST_MOBILE ? { viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true } : {})
  let catalogAvailable = true
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  try {
    await page.route('**/v1/meditation/sessions*', route => route.fulfill({ json: { data: catalogAvailable ? [{ id: sessionId, slug: sessionId, methodId: 'anapanasati', teacherId: 'brahm', titleVi: 'Saved guided practice', durationSeconds: 480, guidanceType: 'guided', language: 'vi', audioUrl: '/audio/Meditation/8%20phut%20HUONG-DAN-THIEN-CAN-BAN.mp3' }] : [] } }))
    await page.goto(base)
    const nav = name => page.getByRole('navigation', { name: 'Điều hướng chính' }).getByRole('button', { name, exact: true }).click()
    const saved = () => page.evaluate(id => JSON.parse(localStorage.getItem('con-duong-xua:practice-history')).find(record => record.sessionId === id), sessionId)
    const guided = () => page.locator(`audio[data-id="${sessionId}"]`)
    const close = () => page.getByRole('button', { name: 'Đóng buổi thiền' }).click()
    const openContinue = () => page.locator('.continue-practice__main').click()
    const startNew = async () => {
      await page.getByRole('button', { name: '8 phút', exact: true }).click()
      await page.locator('.quick-guidance__option').first().click()
      await page.locator('.quick-practice-sheet__actions .btn-primary').click()
    }
    await nav('Nghe'); await page.locator('.audio-row__play').first().click()
    await page.waitForFunction(() => [...document.querySelectorAll('audio')].some(el => !el.paused && el.currentTime > .1))
    const listeningId = await page.locator('audio').evaluateAll(els => els.find(el => !el.paused).dataset.id)
    await nav('Thiền'); await startNew()
    await page.waitForFunction(id => [...document.querySelectorAll('audio')].some(el => el.dataset.id === id && !el.paused && el.currentTime > .1), sessionId)
    await guided().evaluate(el => { el.currentTime = 42.75 })
    await close()
    assert.ok(await guided().evaluate(el => el.paused))
    let progress = await saved()
    assert.ok(progress.progressSeconds >= 42.75)
    assert.equal(progress.completed, false)
    assert.equal(progress.paused, true)
    assert.equal(progress.selectedDurationSeconds, 480)
    assert.equal(progress.sessionSnapshot.teacherId, 'brahm')
    assert.equal(progress.sessionSnapshot.titleVi, 'Saved guided practice')
    assert.equal(await page.locator('.mini').count(), 1)
    assert.ok(await page.locator(`audio[data-id="${listeningId}"]`).evaluate(el => el.paused))
    await openContinue()
    assert.ok(await guided().evaluate(el => el.paused))
    const pausedPosition = await guided().evaluate(el => el.currentTime)
    await page.waitForTimeout(400)
    assert.equal(await guided().evaluate(el => el.currentTime), pausedPosition)
    await page.locator('.guided-transport .primary').click()
    await page.waitForFunction(({ id, position }) => [...document.querySelectorAll('audio')].some(el => el.dataset.id === id && !el.paused && el.currentTime > position + .1), { id: sessionId, position: pausedPosition })
    await page.locator('.guided-transport .primary').click()
    await page.locator('.guided-transport button').last().click()
    await close()
    progress = await saved()
    assert.ok(progress.progressSeconds >= pausedPosition + 15)
    assert.equal(progress.completed, false)
    console.log('PASS: Close pauses/saves; Continue opens paused; explicit resume and paused seeking retain progress')

    catalogAvailable = false
    await page.reload()
    await nav('Nghe'); await page.locator('.audio-row__play').first().click()
    await page.waitForFunction(() => [...document.querySelectorAll('audio')].some(el => !el.paused && el.currentTime > .1))
    await nav('Thiền'); await openContinue()
    assert.equal(await page.locator('.meditation-player__identity h2').innerText(), 'Saved guided practice')
    assert.equal(await page.locator('audio').evaluateAll(els => els.filter(el => !el.paused).length), 1)
    assert.ok(await page.locator(`audio[data-id="${listeningId}"]`).evaluate(el => !el.paused))
    // Closing restored, paused meditation must not pause the independent Nghe player.
    await close()
    assert.ok(await page.locator(`audio[data-id="${listeningId}"]`).evaluate(el => !el.paused))
    assert.equal((await saved()).progressSeconds, progress.progressSeconds)
    await openContinue()
    await page.locator('.guided-transport .primary').click()
    await page.waitForFunction(({ id, position }) => [...document.querySelectorAll('audio')].some(el => el.dataset.id === id && !el.paused && el.currentTime >= position), { id: sessionId, position: progress.progressSeconds })
    assert.equal(await page.locator('audio').evaluateAll(els => els.filter(el => !el.paused).length), 1)
    await close()
    console.log('PASS: refresh/catalog unavailable restores the same session and position; Nghe remains independent')

    catalogAvailable = true
    await page.reload(); await nav('Thiền')
    let releaseAudio
    const held = new Promise(resolve => { releaseAudio = resolve })
    await page.route('**/audio/Meditation/8*', async route => { await held; await route.continue().catch(() => {}) })
    await startNew(); await close()
    const immediate = await saved()
    assert.equal(immediate.progressSeconds, 0)
    assert.equal(immediate.paused, true)
    assert.equal(immediate.completed, false)
    assert.equal(await page.locator('.continue-practice__main').count(), 1)
    releaseAudio()
    await page.waitForTimeout(400)
    assert.ok(await guided().evaluate(el => el.paused))
    assert.deepEqual(errors, [])
    console.log('PASS: Close during loading saves a paused, resumable session at zero without ghost audio')
  } finally { await browser.close() }
})().catch(error => { console.error(error); process.exitCode = 1 })
